package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"os"
)

// Decryptor implements the GO side of the GovPay+ data-encryption scheme
// (spec §3, "Security Standards for Data Encryption"):
//
//   - The transaction key is a 32-character AES-256 key generated by GovPay+,
//     RSA-OAEP encrypted with this GO's public key and carried in the
//     "TransactionKey" HTTP header (base64).
//   - Each data[].value of a request is AES-256-GCM encrypted with that
//     transaction key (base64).
//
// The GO decrypts the transaction key with its RSA private key, then decrypts
// each value with the AES key. On the way back it re-encrypts the response
// values with the same AES key so GovPay+ can decrypt them.
//
// Algorithm standards (spec §3.2):
//   - TransactionKey: RSA / OAEP (SHA-256) / 2048-bit.
//   - Payload:        AES / GCM / 256-bit, IV = first 12 bytes of the AES key.
type Decryptor struct {
	priv *rsa.PrivateKey
}

// aesKeyLen is the length, in bytes, of the plaintext AES-256 transaction key
// (a "32-character" key per spec §3.1).
const aesKeyLen = 32

// gcmNonceLen is the GCM IV length: "First 12 bytes of cryptographic key"
// (spec §3.2.2).
const gcmNonceLen = 12

// loadDecryptor reads a PEM-encoded RSA private key (PKCS#8 or PKCS#1) from
// path and returns a Decryptor. The GO cannot serve presentment/update without
// it, so a missing or invalid key is a fatal configuration error.
func loadDecryptor(path string) (*Decryptor, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read private key: %w", err)
	}
	return newDecryptor(data)
}

// newDecryptor builds a Decryptor from a PEM-encoded RSA private key.
func newDecryptor(pemData []byte) (*Decryptor, error) {
	priv, err := parseRSAPrivateKey(pemData)
	if err != nil {
		return nil, err
	}
	return &Decryptor{priv: priv}, nil
}

func parseRSAPrivateKey(pemData []byte) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("private key: no PEM block found")
	}
	if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return key, nil
	}
	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse private key: %w", err)
	}
	key, ok := parsed.(*rsa.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("private key is not RSA")
	}
	return key, nil
}

// DecryptTransactionKey decrypts the base64 RSA-OAEP "TransactionKey" header
// into the 32-byte AES key.
func (d *Decryptor) DecryptTransactionKey(header string) ([]byte, error) {
	ciphertext, err := base64.StdEncoding.DecodeString(header)
	if err != nil {
		return nil, fmt.Errorf("transaction key not base64: %w", err)
	}
	key, err := rsa.DecryptOAEP(sha256.New(), rand.Reader, d.priv, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("rsa decrypt transaction key: %w", err)
	}
	if len(key) != aesKeyLen {
		return nil, fmt.Errorf("transaction key must be %d bytes, got %d", aesKeyLen, len(key))
	}
	return key, nil
}

// DecryptValues decrypts the value of every data[] item in place. Each value is
// expected to be a base64 AES-GCM ciphertext string; the decrypted plaintext
// replaces it.
func (d *Decryptor) DecryptValues(params []Param, key []byte) error {
	for i := range params {
		ciphertext, ok := params[i].Value.(string)
		if !ok {
			return fmt.Errorf("encrypted value for %q must be a string", params[i].ParamName)
		}
		plain, err := aesGCMDecrypt(key, ciphertext)
		if err != nil {
			return fmt.Errorf("decrypt value for %q: %w", params[i].ParamName, err)
		}
		params[i].Value = plain
	}
	return nil
}

// encryptInitialValues re-encrypts the InitialValue of every response object
// with the transaction key so GovPay+ can decrypt them. Values are stringified
// before encryption; nil/empty values are encrypted as empty strings to keep
// the wire shape uniform.
func encryptPresentmentValues(objs []PresentmentObject, key []byte) error {
	for i := range objs {
		enc, err := aesGCMEncrypt(key, valueToString(objs[i].InitialValue))
		if err != nil {
			return err
		}
		objs[i].InitialValue = enc
	}
	return nil
}

func encryptPaymentValues(items []PaymentItem, key []byte) error {
	for i := range items {
		enc, err := aesGCMEncrypt(key, valueToString(items[i].InitialValue))
		if err != nil {
			return err
		}
		items[i].InitialValue = enc
	}
	return nil
}

// valueToString renders a JSON value as the plaintext to encrypt: strings pass
// through unchanged, everything else is JSON-encoded (so 1000.00 -> "1000").
func valueToString(v interface{}) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	default:
		b, err := json.Marshal(t)
		if err != nil {
			return fmt.Sprintf("%v", t)
		}
		return string(b)
	}
}

// aesGCMEncrypt encrypts plaintext with AES-256-GCM using nonce = key[:12]
// (spec §3.2.2) and returns the base64 of (ciphertext||tag).
func aesGCMEncrypt(key []byte, plaintext string) (string, error) {
	gcm, nonce, err := newGCM(key)
	if err != nil {
		return "", err
	}
	sealed := gcm.Seal(nil, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(sealed), nil
}

// aesGCMDecrypt reverses aesGCMEncrypt.
func aesGCMDecrypt(key []byte, b64 string) (string, error) {
	sealed, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return "", fmt.Errorf("value not base64: %w", err)
	}
	gcm, nonce, err := newGCM(key)
	if err != nil {
		return "", err
	}
	plain, err := gcm.Open(nil, nonce, sealed, nil)
	if err != nil {
		return "", fmt.Errorf("gcm open: %w", err)
	}
	return string(plain), nil
}

func newGCM(key []byte) (cipher.AEAD, []byte, error) {
	if len(key) != aesKeyLen {
		return nil, nil, fmt.Errorf("aes key must be %d bytes", aesKeyLen)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, nil, err
	}
	gcm, err := cipher.NewGCMWithNonceSize(block, gcmNonceLen)
	if err != nil {
		return nil, nil, err
	}
	return gcm, key[:gcmNonceLen], nil
}
