package main

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
)

// Decryptor implements the GO side of the GovPay+ data-encryption scheme
// (spec §3, "Security Standards for Data Encryption"):
//
//   - The transaction key is a 32-character AES-256 key generated by GovPay+,
//     RSA-OAEP encrypted with this GO's public key and carried in the
//     "TransactionKey" HTTP header (base64).
//   - Every field of each request data[] element (seq, paramName, value) is
//     AES-256-CBC encrypted with that transaction key (base64).
//
// The GO decrypts the transaction key with its RSA private key, then decrypts
// each field with the AES key. On the way back it encrypts every field of each
// response object with the same AES key so GovPay+ can decrypt them.
//
// Algorithm standards (spec §3.2):
//   - TransactionKey: RSA / OAEP (SHA-256) / MGF1(SHA-256) / 2048-bit.
//   - Payload:        AES / CBC / 256-bit, PKCS7 padding,
//     IV = first 16 bytes of the AES key.
type Decryptor struct {
	priv *rsa.PrivateKey
}

// aesKeyLen is the length, in bytes, of the plaintext AES-256 transaction key
// (a "32-character" key per spec §3.1).
const aesKeyLen = 32

// ivLen is the AES-CBC IV length. Per spec §3.2.2 the IV is the first 16 bytes
// of the transaction key.
const ivLen = 16

// loadDecryptor reads a PEM-encoded RSA private key (PKCS#8 or PKCS#1) from
// path and returns a Decryptor. The GO cannot serve presentment/update without
// it, so a missing or invalid key is a fatal configuration error.
func loadDecryptor(path string) (*Decryptor, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read private key: %w", err)
	}
	return newDecryptor(data)
}

// newDecryptor builds a Decryptor from a PEM-encoded RSA private key.
func newDecryptor(pemData []byte) (*Decryptor, error) {
	priv, err := parseRSAPrivateKey(pemData)
	if err != nil {
		return nil, err
	}
	return &Decryptor{priv: priv}, nil
}

func parseRSAPrivateKey(pemData []byte) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("private key: no PEM block found")
	}
	if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return key, nil
	}
	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse private key: %w", err)
	}
	key, ok := parsed.(*rsa.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("private key is not RSA")
	}
	return key, nil
}

// DecryptTransactionKey decrypts the base64 RSA-OAEP "TransactionKey" header
// into the 32-byte AES key.
func (d *Decryptor) DecryptTransactionKey(header string) ([]byte, error) {
	ciphertext, err := base64.StdEncoding.DecodeString(header)
	if err != nil {
		return nil, fmt.Errorf("transaction key not base64: %w", err)
	}
	key, err := rsa.DecryptOAEP(sha256.New(), rand.Reader, d.priv, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("rsa decrypt transaction key: %w", err)
	}
	if len(key) != aesKeyLen {
		return nil, fmt.Errorf("transaction key must be %d bytes, got %d", aesKeyLen, len(key))
	}
	return key, nil
}

// DecryptParams decrypts every field (seq, paramName, value) of each request
// data[] item in place. Each field is a base64 AES-CBC ciphertext string; the
// decrypted plaintext replaces it (spec §3.1: GovPay+ encrypts all three).
func (d *Decryptor) DecryptParams(params []Param, key []byte) error {
	for i := range params {
		seq, err := aesCBCDecrypt(key, params[i].Seq)
		if err != nil {
			return fmt.Errorf("decrypt seq: %w", err)
		}
		params[i].Seq = seq

		name, err := aesCBCDecrypt(key, params[i].ParamName)
		if err != nil {
			return fmt.Errorf("decrypt paramName: %w", err)
		}
		params[i].ParamName = name

		ciphertext, ok := params[i].Value.(string)
		if !ok {
			return fmt.Errorf("encrypted value for %q must be a string", params[i].ParamName)
		}
		plain, err := aesCBCDecrypt(key, ciphertext)
		if err != nil {
			return fmt.Errorf("decrypt value for %q: %w", params[i].ParamName, err)
		}
		params[i].Value = plain
	}
	return nil
}

// encryptPresentmentValues encrypts every field of every response object with
// the transaction key so GovPay+ can decrypt them (spec §3.1.7). Empty fields
// are encrypted as empty strings to keep the wire shape uniform.
func encryptPresentmentValues(objs []PresentmentObject, key []byte) error {
	for i := range objs {
		if err := encryptPresentmentObject(&objs[i], key); err != nil {
			return err
		}
	}
	return nil
}

func encryptPresentmentObject(o *PresentmentObject, key []byte) error {
	if err := encryptFields(key,
		&o.ObjType, &o.Seq, &o.ID, &o.Placeholder, &o.InitialValue,
		&o.DataType, &o.MaxLength, &o.SelectionType, &o.Mask, &o.NotNull,
		&o.Enabled, &o.Returned, &o.Rows, &o.Cols, &o.ReturnParam,
		&o.IsPaymentReference, &o.IsPaymentAmount, &o.ReturnValue,
	); err != nil {
		return err
	}
	return encryptObjExtras(key, o.ObjData, o.TableData)
}

func encryptPaymentValues(items []PaymentItem, key []byte) error {
	for i := range items {
		if err := encryptFields(key,
			&items[i].ObjType, &items[i].Seq, &items[i].ID, &items[i].Placeholder,
			&items[i].InitialValue, &items[i].DataType, &items[i].MaxLength,
			&items[i].SelectionType, &items[i].Mask, &items[i].NotNull,
			&items[i].Enabled, &items[i].Returned, &items[i].Rows, &items[i].Cols,
			&items[i].ReturnParam, &items[i].ReturnValue,
		); err != nil {
			return err
		}
		if err := encryptObjExtras(key, nil, items[i].TableData); err != nil {
			return err
		}
	}
	return nil
}

// encryptObjExtras encrypts the nested string fields of any combo items and
// table data attached to a response object. These are empty in the current
// bill flows but are handled so "every field" holds for combo/table objects.
func encryptObjExtras(key []byte, objData []ComboItem, table *TableDataObject) error {
	for j := range objData {
		if err := encryptFields(key, &objData[j].ID, &objData[j].Data); err != nil {
			return err
		}
	}
	if table != nil {
		for j := range table.Header {
			if err := encryptFields(key, &table.Header[j].DataType, &table.Header[j].Value, &table.Header[j].Enabled); err != nil {
				return err
			}
		}
		for j := range table.RowData {
			if err := encryptFields(key, &table.RowData[j].DataType, &table.RowData[j].Value, &table.RowData[j].Enabled); err != nil {
				return err
			}
		}
	}
	return nil
}

// encryptFields AES-CBC encrypts each referenced string in place.
func encryptFields(key []byte, fields ...*string) error {
	for _, f := range fields {
		enc, err := aesCBCEncrypt(key, *f)
		if err != nil {
			return err
		}
		*f = enc
	}
	return nil
}

// aesCBCEncrypt encrypts plaintext with AES-256-CBC and PKCS7 padding, using
// IV = key[:16] (spec §3.2.2), and returns the base64 of the ciphertext.
func aesCBCEncrypt(key []byte, plaintext string) (string, error) {
	block, iv, err := newCBC(key)
	if err != nil {
		return "", err
	}
	padded := pkcs7Pad([]byte(plaintext), block.BlockSize())
	ciphertext := make([]byte, len(padded))
	cipher.NewCBCEncrypter(block, iv).CryptBlocks(ciphertext, padded)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

// aesCBCDecrypt reverses aesCBCEncrypt.
func aesCBCDecrypt(key []byte, b64 string) (string, error) {
	ciphertext, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return "", fmt.Errorf("value not base64: %w", err)
	}
	block, iv, err := newCBC(key)
	if err != nil {
		return "", err
	}
	if len(ciphertext) == 0 || len(ciphertext)%block.BlockSize() != 0 {
		return "", fmt.Errorf("ciphertext is not a whole number of blocks")
	}
	plaintext := make([]byte, len(ciphertext))
	cipher.NewCBCDecrypter(block, iv).CryptBlocks(plaintext, ciphertext)
	unpadded, err := pkcs7Unpad(plaintext, block.BlockSize())
	if err != nil {
		return "", err
	}
	return string(unpadded), nil
}

// newCBC returns an AES cipher block and the IV (first 16 bytes of the key).
func newCBC(key []byte) (cipher.Block, []byte, error) {
	if len(key) != aesKeyLen {
		return nil, nil, fmt.Errorf("aes key must be %d bytes", aesKeyLen)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, nil, err
	}
	return block, key[:ivLen], nil
}

// pkcs7Pad appends PKCS7 padding so the data is a whole number of blocks.
func pkcs7Pad(data []byte, blockSize int) []byte {
	pad := blockSize - len(data)%blockSize
	return append(data, bytes.Repeat([]byte{byte(pad)}, pad)...)
}

// pkcs7Unpad removes and validates PKCS7 padding.
func pkcs7Unpad(data []byte, blockSize int) ([]byte, error) {
	n := len(data)
	if n == 0 || n%blockSize != 0 {
		return nil, fmt.Errorf("invalid padded length")
	}
	pad := int(data[n-1])
	if pad == 0 || pad > blockSize {
		return nil, fmt.Errorf("invalid padding")
	}
	for _, b := range data[n-pad:] {
		if int(b) != pad {
			return nil, fmt.Errorf("invalid padding")
		}
	}
	return data[:n-pad], nil
}
